name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write  # ✅ Grant write permission to create a release

jobs:
  release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive with Version
        run: |
          VERSION=${{ github.ref_name }}
          zip -r "apply_qml_style_${VERSION}.zip" . -x "*.git*" ".github/*"

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "" > release_notes.md
          git log --pretty=format:"- %s" $(git rev-list --tags --max-count=1 2>/dev/null || echo HEAD)..HEAD >> release_notes.md

      - name: Create GitHub Release with Verified Signature
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" "apply_qml_style_${{ github.ref_name }}.zip" \
            --title "Release ${{ github.ref_name }}" \
            --notes-file release_notes.md \
            --verify-tag
